-- DROP TABLE IF EXISTS users;
--
-- CREATE TABLE users
-- (
--     id       LONG AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(255) NOT NULL
--
-- );
--
-- INSERT INTO users (id, username)
-- VALUES (1, 'DaisyDuck'),
--        (2, 'DanielDüsentrieb'),
--        (3, 'GustavGans');